@startuml

header
green lines mean: at least stub functionality is working
endheader

package "github.com/uhi22/pyPLC" {
	package "pyPlcIPv6" {
		[miniIPv6]
		[pyPlcUdp]
		[pyPlcSDP]
		[pyPlcTcpExiSniff]
	}

	package "pyPlcHomeplug" {
		[dispatcher]
		[SLAC]
	}
	
	[fsmEvse \nThe charger state machine.] as fsmEvse
	[fsmPev \nThe car state machine.] as fsmPev
	[exiConnector.py] as exiConnector

	package "pyPlcTcpSocket" {
		[pyPlcTcpServerSocket]
		[pyPlcTcpClientSocket]
	}
	
}

[ControlPilotLine]
[HomeplugAdaptor]
[pcap DLL] as pcap
[wireshark]

package "github.com/uhi22/OpenV2Gx" {
	[OpenV2Gx.exe \nEncodes and Decodes EXI data via command line interface.] as dec
}

package "WindowsOS or Linux" {
  [OS_Ethernet]
  [OS_IPv6]
  [OS_TCP]
  [OS_ICMP]
}

[ControlPilotLine] <-[#green]up-> [HomeplugAdaptor]
[ControlPilotLine] <-[#green]up-> [PWM-Generator]
[HomeplugAdaptor] <-[#green]up-> [OS_Ethernet]
[OS_Ethernet] <-[#green]up-> [pcap]
[OS_Ethernet] <-[#green]up-> [OS_IPv6]
[OS_Ethernet] <-[#green]up-> [OS_ICMP]
[OS_IPv6] <-[#green]up-> [OS_TCP]

[pcap] <-[#green]up-> [pcap-ct]
[pcap] -[#green]up-> [wireshark]
[pcap-ct] <-[#green]up-> [dispatcher]
[dispatcher] <-[#green]up-> [SLAC]
[dispatcher] <-[#green]up-> [miniIPv6]
[miniIPv6] <-[#green]up-> [pyPlcUdp]
[miniIPv6] -up-> [pyPlcTcpExiSniff]
[pyPlcUdp] <-[#green]up-> [pyPlcSDP]
[OS_TCP] <-[#green]up-> [pyPlcTcpServerSocket]
[OS_TCP] <-[#green]up-> [pyPlcTcpClientSocket]
[pyPlcTcpServerSocket] <-[#green]up-> [fsmEvse]
[pyPlcTcpClientSocket] <-[#green]up-> [fsmPev]
[fsmEvse] <-[#green]r-> [exiConnector]
[fsmPev] <-[#green]r-> [exiConnector]
[dec] <-[#green]up-> [exiConnector]
[dec] -l-> [pyPlcTcpExiSniff] 
@enduml